redis:
  redis-cli: -h ${host} -p ${port} -a ${password}

mysql:
  mysql: --protocol=TCP --host=${host} --port=${port} --user=${user} --password=${password} ${name}
  mysqldump: --protocol=TCP --host=${host} --port=${port} --user=${user} --password=${password} ${name} > ${Output file}

mongodb:
  mongo: --host ${host} --port ${port} -u ${user} -p ${password} ${name}
  mongodump: --host ${host} --port ${port} -u ${user} -p ${password} --db ${name}
  mongorestore: --host ${host} --port ${port} -u ${user} -p ${password} --db ${name} ${Directory or filename to restore from}

postgresql:
  psql:
    command: -h ${host} -p ${port} -d ${name} -U ${user} -w
    environment:
      - PGPASSWORD='${password}'
